version: '3.9'

services:
  atelier-catmash:
    build:
      target: npm-dev
      context: .
    command: sh -c "npm install && npm run start"
    ports:
      - '4200:4200'
    # tty and stdin_open are needed to use debugger inside docker
    stdin_open: true
    tty: true
    volumes:
      - .:/app
